---
kind: pipeline
type: exec
name: flake info

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: show flake info
  commands:
  - nix --experimental-features "nix-command flakes" flake show
  - nix --experimental-features "nix-command flakes" flake metadata

- name: run flake checks
  commands:
  - nix --experimental-features "nix-command flakes" flake check --show-trace

---
kind: pipeline
type: exec
name: build amd64 hosts

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: build aida
  commands:
  - nix build '.#nixosConfigurations.aida.config.system.build.toplevel' --out-link result-aida
  - nix path-info --closure-size -h $(readlink -f result-aida)

- name: build deke
  commands:
  - nix build '.#nixosConfigurations.deke.config.system.build.toplevel' --out-link result-deke
  - nix path-info --closure-size -h $(readlink -f result-deke)

- name: build flint
  commands:
  - nix build '.#nixosConfigurations.flint.config.system.build.toplevel' --out-link result-flint
  - nix path-info --closure-size -h $(readlink -f result-flint)

- name: build kora
  commands:
  - nix build '.#nixosConfigurations.kora.config.system.build.toplevel' --out-link result-kora
  - nix path-info --closure-size -h $(readlink -f result-kora)

- name: build simmons
  commands:
  - nix build '.#nixosConfigurations.simmons.config.system.build.toplevel' --out-link result-simmons
  - nix path-info --closure-size -h $(readlink -f result-simmons)

- name: build snowflake
  commands:
  - nix build '.#nixosConfigurations.snowflake.config.system.build.toplevel' --out-link result-snowflake
  - nix path-info --closure-size -h $(readlink -f result-snowflake)

- name: build stone
  commands:
  - nix build '.#nixosConfigurations.stone.config.system.build.toplevel' --out-link result-stone
  - nix path-info --closure-size -h $(readlink -f result-stone)

- name: build the-bus
  commands:
  - nix build '.#nixosConfigurations.the-bus.config.system.build.toplevel' --out-link result-the-bus
  - nix path-info --closure-size -h $(readlink -f result-the-bus)

- name: build the-hub
  commands:
  - nix build '.#nixosConfigurations.the-hub.config.system.build.toplevel' --out-link result-the-hub
  - nix path-info --closure-size -h $(readlink -f result-the-hub)

- name: upload to binary cache via s3
  commands:
  - nix run 'github:mayniklas/nixos'#s3uploader
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

trigger:
  branch:
  - main
  event:
  - cron
  - push
  - pull_request

---
kind: pipeline
type: exec
name: build amd64 flake apps

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: Build drone-gen
  commands:
  - nix build .#drone-gen --out-link result-drone-gen
  - nix path-info --closure-size -h $(readlink -f result-drone-gen)

- name: Build s3uploader
  commands:
  - nix build .#s3uploader --out-link result-s3uploader
  - nix path-info --closure-size -h $(readlink -f result-s3uploader)

- name: Build vs-fix
  commands:
  - nix build .#vs-fix --out-link result-vs-fix
  - nix path-info --closure-size -h $(readlink -f result-vs-fix)

- name: upload to binary cache via s3
  commands:
  - nix run 'github:mayniklas/nixos'#s3uploader
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

trigger:
  branch:
  - main
  event:
  - push
  - cron
  - pull_request

---
kind: pipeline
type: exec
name: build arm64 flake apps

platform:
  os: linux
  arch: arm64

clone:
  depth: 1

steps:

- name: Build drone-gen
  commands:
  - nix build .#drone-gen --out-link result-drone-gen
  - nix path-info --closure-size -h $(readlink -f result-drone-gen)

- name: Build s3uploader
  commands:
  - nix build .#s3uploader --out-link result-s3uploader
  - nix path-info --closure-size -h $(readlink -f result-s3uploader)

- name: Build vs-fix
  commands:
  - nix build .#vs-fix --out-link result-vs-fix
  - nix path-info --closure-size -h $(readlink -f result-vs-fix)

- name: upload to binary cache via s3
  commands:
  - nix run 'github:mayniklas/nixos'#s3uploader
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

trigger:
  branch:
  - main
  event:
  - push
  - cron
  - pull_request

