---
kind: pipeline
type: exec
name: flake info

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: show flake info
  commands:
  - nix --experimental-features "nix-command flakes" flake show
  - nix --experimental-features "nix-command flakes" flake metadata

- name: run flake checks
  commands:
  - nix --experimental-features "nix-command flakes" flake check --show-trace

---
kind: pipeline
type: exec
name: build aida

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: build aida
  commands:
  - nix build -v '.#nixosConfigurations.aida.config.system.build.toplevel'

- name: show closure size
  commands:
  - nix path-info --closure-size -h $(readlink -f result)

- name: upload aida to binary cache via s3
  commands:
  - nix copy --to 's3://nix-cache?scheme=https&region=eu-central-1&endpoint=s3.lounge.rocks' $(nix-store -qR result/) -L
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

trigger:
  branch:
  - main
  - update-flake
  event:
  - cron
  - push
  - pull_request

---
kind: pipeline
type: exec
name: build deke

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: build deke
  commands:
  - nix build -v '.#nixosConfigurations.deke.config.system.build.toplevel'

- name: show closure size
  commands:
  - nix path-info --closure-size -h $(readlink -f result)

- name: upload deke to binary cache via s3
  commands:
  - nix copy --to 's3://nix-cache?scheme=https&region=eu-central-1&endpoint=s3.lounge.rocks' $(nix-store -qR result/) -L
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

trigger:
  branch:
  - main
  - update-flake
  event:
  - cron
  - push
  - pull_request

---
kind: pipeline
type: exec
name: build flint

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: build flint
  commands:
  - nix build -v '.#nixosConfigurations.flint.config.system.build.toplevel'

- name: show closure size
  commands:
  - nix path-info --closure-size -h $(readlink -f result)

- name: upload flint to binary cache via s3
  commands:
  - nix copy --to 's3://nix-cache?scheme=https&region=eu-central-1&endpoint=s3.lounge.rocks' $(nix-store -qR result/) -L
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

trigger:
  branch:
  - main
  - update-flake
  event:
  - cron
  - push
  - pull_request

---
kind: pipeline
type: exec
name: build kora

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: build kora
  commands:
  - nix build -v '.#nixosConfigurations.kora.config.system.build.toplevel'

- name: show closure size
  commands:
  - nix path-info --closure-size -h $(readlink -f result)

- name: upload kora to binary cache via s3
  commands:
  - nix copy --to 's3://nix-cache?scheme=https&region=eu-central-1&endpoint=s3.lounge.rocks' $(nix-store -qR result/) -L
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

trigger:
  branch:
  - main
  - update-flake
  event:
  - cron
  - push
  - pull_request

---
kind: pipeline
type: exec
name: build simmons

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: build simmons
  commands:
  - nix build -v '.#nixosConfigurations.simmons.config.system.build.toplevel'

- name: show closure size
  commands:
  - nix path-info --closure-size -h $(readlink -f result)

- name: upload simmons to binary cache via s3
  commands:
  - nix copy --to 's3://nix-cache?scheme=https&region=eu-central-1&endpoint=s3.lounge.rocks' $(nix-store -qR result/) -L
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

trigger:
  branch:
  - main
  - update-flake
  event:
  - cron
  - push
  - pull_request

---
kind: pipeline
type: exec
name: build snowflake

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: build snowflake
  commands:
  - nix build -v '.#nixosConfigurations.snowflake.config.system.build.toplevel'

- name: show closure size
  commands:
  - nix path-info --closure-size -h $(readlink -f result)

- name: upload snowflake to binary cache via s3
  commands:
  - nix copy --to 's3://nix-cache?scheme=https&region=eu-central-1&endpoint=s3.lounge.rocks' $(nix-store -qR result/) -L
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

trigger:
  branch:
  - main
  - update-flake
  event:
  - cron
  - push
  - pull_request

---
kind: pipeline
type: exec
name: build the-bus

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: build the-bus
  commands:
  - nix build -v '.#nixosConfigurations.the-bus.config.system.build.toplevel'

- name: show closure size
  commands:
  - nix path-info --closure-size -h $(readlink -f result)

- name: upload the-bus to binary cache via s3
  commands:
  - nix copy --to 's3://nix-cache?scheme=https&region=eu-central-1&endpoint=s3.lounge.rocks' $(nix-store -qR result/) -L
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

trigger:
  branch:
  - main
  - update-flake
  event:
  - cron
  - push
  - pull_request

---
kind: pipeline
type: exec
name: build the-hub

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: build the-hub
  commands:
  - nix build -v '.#nixosConfigurations.the-hub.config.system.build.toplevel'

- name: show closure size
  commands:
  - nix path-info --closure-size -h $(readlink -f result)

- name: upload the-hub to binary cache via s3
  commands:
  - nix copy --to 's3://nix-cache?scheme=https&region=eu-central-1&endpoint=s3.lounge.rocks' $(nix-store -qR result/) -L
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

trigger:
  branch:
  - main
  - update-flake
  event:
  - cron
  - push
  - pull_request

---
kind: pipeline
type: exec
name: build water-on-fire

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: build water-on-fire
  commands:
  - nix build -v '.#nixosConfigurations.water-on-fire.config.system.build.toplevel'

- name: show closure size
  commands:
  - nix path-info --closure-size -h $(readlink -f result)

- name: upload water-on-fire to binary cache via s3
  commands:
  - nix copy --to 's3://nix-cache?scheme=https&region=eu-central-1&endpoint=s3.lounge.rocks' $(nix-store -qR result/) -L
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

trigger:
  branch:
  - main
  - update-flake
  event:
  - cron
  - push
  - pull_request

---
kind: pipeline
type: exec
name: build amd64 flake apps

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: Build owncast
  commands:
  - nix build .#owncast
  - nix copy --to 's3://example-nix-cache?scheme=https&region=eu-central-1&endpoint=s3.lounge.rocks' $(nix-store -qR result/) -L
  - nix path-info --closure-size -h $(readlink -f result)
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

- name: Build plexRaw
  commands:
  - nix build .#plexRaw
  - nix copy --to 's3://example-nix-cache?scheme=https&region=eu-central-1&endpoint=s3.lounge.rocks' $(nix-store -qR result/) -L
  - nix path-info --closure-size -h $(readlink -f result)
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

- name: Build tautulli
  commands:
  - nix build .#tautulli
  - nix copy --to 's3://example-nix-cache?scheme=https&region=eu-central-1&endpoint=s3.lounge.rocks' $(nix-store -qR result/) -L
  - nix path-info --closure-size -h $(readlink -f result)
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

trigger:
  branch:
  - main
  event:
  - push
  - cron
  - pull_request

---
kind: pipeline
type: exec
name: build arm64 flake apps

platform:
  os: linux
  arch: arm64

clone:
  depth: 1

steps:

- name: Build owncast
  commands:
  - nix build .#owncast
  - nix copy --to 's3://example-nix-cache?scheme=https&region=eu-central-1&endpoint=s3.lounge.rocks' $(nix-store -qR result/) -L
  - nix path-info --closure-size -h $(readlink -f result)
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

trigger:
  branch:
  - main
  event:
  - push
  - cron
  - pull_request

