---
kind: pipeline
type: exec
name: flake info

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

  - name: show flake show
    commands:
      - nix flake show

  - name: show flake info
    commands:
      - nix flake info

  - name: run flake checks
    commands:
      - nix flake check

trigger:
  branch:
  - main
  event:
  - push
  - cron
  - pull_request

---
kind: pipeline
type: exec
name: build amd64 hosts

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: build aida
  commands:
  - nix build '.#nixosConfigurations.aida.config.system.build.toplevel' --out-link result-aida
  - nix path-info --closure-size -h $(readlink -f result-aida)

- name: build daisy
  commands:
  - nix build '.#nixosConfigurations.daisy.config.system.build.toplevel' --out-link result-daisy
  - nix path-info --closure-size -h $(readlink -f result-daisy)

- name: build deke
  commands:
  - nix build '.#nixosConfigurations.deke.config.system.build.toplevel' --out-link result-deke
  - nix path-info --closure-size -h $(readlink -f result-deke)

- name: build kora
  commands:
  - nix build '.#nixosConfigurations.kora.config.system.build.toplevel' --out-link result-kora
  - nix path-info --closure-size -h $(readlink -f result-kora)

- name: build simmons
  commands:
  - nix build '.#nixosConfigurations.simmons.config.system.build.toplevel' --out-link result-simmons
  - nix path-info --closure-size -h $(readlink -f result-simmons)

- name: build snowflake
  commands:
  - nix build '.#nixosConfigurations.snowflake.config.system.build.toplevel' --out-link result-snowflake
  - nix path-info --closure-size -h $(readlink -f result-snowflake)

- name: build the-bus
  commands:
  - nix build '.#nixosConfigurations.the-bus.config.system.build.toplevel' --out-link result-the-bus
  - nix path-info --closure-size -h $(readlink -f result-the-bus)

- name: build the-hub
  commands:
  - nix build '.#nixosConfigurations.the-hub.config.system.build.toplevel' --out-link result-the-hub
  - nix path-info --closure-size -h $(readlink -f result-the-hub)

- name: build usb-desktop
  commands:
  - nix build '.#nixosConfigurations.usb-desktop.config.system.build.toplevel' --out-link result-usb-desktop
  - nix path-info --closure-size -h $(readlink -f result-usb-desktop)

- name: Push amd64 hosts to cachix
  commands:
  - nix build '.#nixosConfigurations.aida.config.system.build.toplevel' --json | jq -r '.[].outputs | to_entries[].value' | cachix push mayniklas
  - nix build '.#nixosConfigurations.daisy.config.system.build.toplevel' --json | jq -r '.[].outputs | to_entries[].value' | cachix push mayniklas
  - nix build '.#nixosConfigurations.deke.config.system.build.toplevel' --json | jq -r '.[].outputs | to_entries[].value' | cachix push mayniklas
  - nix build '.#nixosConfigurations.kora.config.system.build.toplevel' --json | jq -r '.[].outputs | to_entries[].value' | cachix push mayniklas
  - nix build '.#nixosConfigurations.simmons.config.system.build.toplevel' --json | jq -r '.[].outputs | to_entries[].value' | cachix push mayniklas
  - nix build '.#nixosConfigurations.snowflake.config.system.build.toplevel' --json | jq -r '.[].outputs | to_entries[].value' | cachix push mayniklas
  - nix build '.#nixosConfigurations.the-bus.config.system.build.toplevel' --json | jq -r '.[].outputs | to_entries[].value' | cachix push mayniklas
  - nix build '.#nixosConfigurations.the-hub.config.system.build.toplevel' --json | jq -r '.[].outputs | to_entries[].value' | cachix push mayniklas
  - nix build '.#nixosConfigurations.usb-desktop.config.system.build.toplevel' --json | jq -r '.[].outputs | to_entries[].value' | cachix push mayniklas
  environment:
    CACHIX_AUTH_TOKEN:
      from_secret: CACHIX_AUTH_TOKEN

- name: upload to binary cache via s3
  commands:
  - nix run 'github:mayniklas/nixos'#s3uploader
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

trigger:
  branch:
  - main
  event:
  - cron
  - push

---
kind: pipeline
type: exec
name: build amd64 flake apps

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: Build build-system
  commands:
  - nix build .#build-system --out-link result-build-system
  - nix path-info --closure-size -h $(readlink -f result-build-system)

- name: Build drone-gen
  commands:
  - nix build .#drone-gen --out-link result-drone-gen
  - nix path-info --closure-size -h $(readlink -f result-drone-gen)

- name: Build s3uploader
  commands:
  - nix build .#s3uploader --out-link result-s3uploader
  - nix path-info --closure-size -h $(readlink -f result-s3uploader)

- name: Build vs-fix
  commands:
  - nix build .#vs-fix --out-link result-vs-fix
  - nix path-info --closure-size -h $(readlink -f result-vs-fix)

- name: Push amd64 apps to cachix
  commands:
  - nix build .#build-system --json | jq -r '.[].outputs | to_entries[].value' | cachix push mayniklas
  - nix build .#drone-gen --json | jq -r '.[].outputs | to_entries[].value' | cachix push mayniklas
  - nix build .#s3uploader --json | jq -r '.[].outputs | to_entries[].value' | cachix push mayniklas
  - nix build .#vs-fix --json | jq -r '.[].outputs | to_entries[].value' | cachix push mayniklas
  environment:
    CACHIX_AUTH_TOKEN:
      from_secret: CACHIX_AUTH_TOKEN

- name: upload to binary cache via s3
  commands:
  - nix run 'github:mayniklas/nixos'#s3uploader
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

trigger:
  branch:
  - main
  event:
  - push
  - cron

---
kind: pipeline
type: exec
name: build arm64 flake apps

platform:
  os: linux
  arch: arm64

clone:
  depth: 1

steps:

- name: Build build-system
  commands:
  - nix build .#build-system --out-link result-build-system
  - nix path-info --closure-size -h $(readlink -f result-build-system)

- name: Build drone-gen
  commands:
  - nix build .#drone-gen --out-link result-drone-gen
  - nix path-info --closure-size -h $(readlink -f result-drone-gen)

- name: Build s3uploader
  commands:
  - nix build .#s3uploader --out-link result-s3uploader
  - nix path-info --closure-size -h $(readlink -f result-s3uploader)

- name: Build update-input
  commands:
  - nix build .#update-input --out-link result-update-input
  - nix path-info --closure-size -h $(readlink -f result-update-input)

- name: Build vs-fix
  commands:
  - nix build .#vs-fix --out-link result-vs-fix
  - nix path-info --closure-size -h $(readlink -f result-vs-fix)

- name: Push arm64 apps to cachix
  commands:
  - nix build .#build-system --json | jq -r '.[].outputs | to_entries[].value' | cachix push mayniklas
  - nix build .#drone-gen --json | jq -r '.[].outputs | to_entries[].value' | cachix push mayniklas
  - nix build .#s3uploader --json | jq -r '.[].outputs | to_entries[].value' | cachix push mayniklas
  - nix build .#update-input --json | jq -r '.[].outputs | to_entries[].value' | cachix push mayniklas
  - nix build .#vs-fix --json | jq -r '.[].outputs | to_entries[].value' | cachix push mayniklas
  environment:
    CACHIX_AUTH_TOKEN:
      from_secret: CACHIX_AUTH_TOKEN

- name: upload to binary cache via s3
  commands:
  - nix run 'github:mayniklas/nixos'#s3uploader
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

trigger:
  branch:
  - main
  event:
  - push
  - cron

---
kind: pipeline
type: exec
name: build hosts - amd64 (PR)

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: Build aida
  commands:
  - nix build .#aida --out-link result-aida
  - nix path-info --closure-size -h $(readlink -f result-aida)

- name: Build daisy
  commands:
  - nix build .#daisy --out-link result-daisy
  - nix path-info --closure-size -h $(readlink -f result-daisy)

- name: Build deke
  commands:
  - nix build .#deke --out-link result-deke
  - nix path-info --closure-size -h $(readlink -f result-deke)

- name: Build kora
  commands:
  - nix build .#kora --out-link result-kora
  - nix path-info --closure-size -h $(readlink -f result-kora)

- name: Build simmons
  commands:
  - nix build .#simmons --out-link result-simmons
  - nix path-info --closure-size -h $(readlink -f result-simmons)

- name: Build snowflake
  commands:
  - nix build .#snowflake --out-link result-snowflake
  - nix path-info --closure-size -h $(readlink -f result-snowflake)

- name: Build the-bus
  commands:
  - nix build .#the-bus --out-link result-the-bus
  - nix path-info --closure-size -h $(readlink -f result-the-bus)

- name: Build the-hub
  commands:
  - nix build .#the-hub --out-link result-the-hub
  - nix path-info --closure-size -h $(readlink -f result-the-hub)

- name: Build usb-desktop
  commands:
  - nix build .#usb-desktop --out-link result-usb-desktop
  - nix path-info --closure-size -h $(readlink -f result-usb-desktop)

trigger:
  branch:
  - main
  event:
  - pull_request

---
kind: pipeline
type: exec
name: build packages - amd64 (PR)

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: Build build-system
  commands:
  - nix build .#build-system --out-link result-build-system
  - nix path-info --closure-size -h $(readlink -f result-build-system)

- name: Build drone-gen
  commands:
  - nix build .#drone-gen --out-link result-drone-gen
  - nix path-info --closure-size -h $(readlink -f result-drone-gen)

- name: Build s3uploader
  commands:
  - nix build .#s3uploader --out-link result-s3uploader
  - nix path-info --closure-size -h $(readlink -f result-s3uploader)

- name: Build vs-fix
  commands:
  - nix build .#vs-fix --out-link result-vs-fix
  - nix path-info --closure-size -h $(readlink -f result-vs-fix)

trigger:
  branch:
  - main
  event:
  - pull_request

---
kind: pipeline
type: exec
name: build packages - arm64 (PR)

platform:
  os: linux
  arch: arm64

clone:
  depth: 1

steps:

- name: Build build-system
  commands:
  - nix build .#build-system --out-link result-build-system
  - nix path-info --closure-size -h $(readlink -f result-build-system)

- name: Build drone-gen
  commands:
  - nix build .#drone-gen --out-link result-drone-gen
  - nix path-info --closure-size -h $(readlink -f result-drone-gen)

- name: Build s3uploader
  commands:
  - nix build .#s3uploader --out-link result-s3uploader
  - nix path-info --closure-size -h $(readlink -f result-s3uploader)

- name: Build update-input
  commands:
  - nix build .#update-input --out-link result-update-input
  - nix path-info --closure-size -h $(readlink -f result-update-input)

- name: Build vs-fix
  commands:
  - nix build .#vs-fix --out-link result-vs-fix
  - nix path-info --closure-size -h $(readlink -f result-vs-fix)

trigger:
  branch:
  - main
  event:
  - pull_request
