kind: pipeline
type: exec
name: Build all hosts

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: Show flake info
  commands:
  - nix --experimental-features "nix-command flakes" flake show
  - nix --experimental-features "nix-command flakes" flake metadata

- name: Run flake checks
  commands:
  - nix --experimental-features "nix-command flakes" flake check --show-trace

- name: Build quinjet
  commands:
  - nix build '.#nixosConfigurations.quinjet.config.system.build.toplevel'

- name: Build the-bus
  commands:
  - nix build '.#nixosConfigurations.the-bus.config.system.build.toplevel'

- name: Build water-on-fire
  commands:
  - nix build '.#nixosConfigurations.water-on-fire.config.system.build.toplevel'
  
trigger:
  branch:
  - main
  - update-flake
  event:
  - push
  - cron

---
kind: pipeline
name: build check
type: docker

platform:
  os: linux
  arch: amd64

steps:
# - name: Show flake info
#   image: nixpkgs/nix-flakes
#   commands:
#   - nix --experimental-features "nix-command flakes" flake show
#   - nix --experimental-features "nix-command flakes" flake info
#   - nix --experimental-features "nix-command flakes" flake list-inputs
#   environment:
#     NIX_PATH: nixpkgs=channel:nixos-unstable

- name: Run flake checks
  image: nixpkgs/nix-flakes
  commands:
  - nix --experimental-features "nix-command flakes" flake check --show-trace
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable

- name: Build all hosts
  image: nixpkgs/nix-flakes
  commands:
  - nix-build krops.nix -A all
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable

- name: notify on failure
  image: drillster/drone-email
  settings:
    username: apikey
    from:
      from_secret: email_from
    host:
      from_secret: email_host
    password:
      from_secret: email_password
  when:
    status:
    - failure

trigger:
  branch:
    exclude:
    - update-flake

---
kind: pipeline
name: flake update
type: docker

steps:
- name: Update flake.lock
  image: nixpkgs/nix-flakes
  commands:
  - nix flake update
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable

- name: Push updated flake.lock
  image: appleboy/drone-git-push
  settings:
    branch: update-flake
    remote: git@github.com:MayNiklas/nixos.git
    force: true
    commit: true
    force: true
    commit_message: "❄️ Update flake.lock"
    ssh_key:
      from_secret: deploy_key

- name: notify on failure
  image: drillster/drone-email
  settings:
    username: apikey
    from:
      from_secret: email_from
    host:
      from_secret: email_host
    password:
      from_secret: email_password
  when:
    status:
    - failure

trigger:
  branch:
  - main
  event:
  - push
  - cron
