---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: Build water-on-fire
  image: nixpkgs/nix-flakes
  commands:
  - nix-build ./krops.nix -A water-on-fire
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable

- name: Build quinjet
  image: nixpkgs/nix-flakes
  commands:
  - nix-build ./krops.nix -A quinjet
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable
    
- name: Build the-bus
  image: nixpkgs/nix-flakes
  commands:
  - nix-build ./krops.nix -A the-bus
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable

- name: notify
  image: drillster/drone-email
  settings:
    username: apikey
    from:
      from_secret: email_from
    host:
      from_secret: email_host
    password:
      from_secret: email_password
  depends_on:
  - Build water-on-fire
  - Build quinjet
  - Build the-bus
