---
- name: tasks
  hosts: localhost
  vars:
    - apt_packages:
        - git
        - nano
        - tzdata
        - zsh
        - locales
        - curl
        - xz-utils
        - ca-certificates

  tasks:
  
  - name: Upgrade all packages to the latest version
    apt:
      update_cache: yes
      name: "*"
      state: latest

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes

  - name: "Install packages defined in apt_packages"
    apt:
      name: "{{ item }}"
      state: latest
    loop: "{{ apt_packages }}"
    when: apt_packages|default([])|count > 0

  - name: prepare for Nix install
    ansible.builtin.shell: |
      mkdir -m 0755 /nix && groupadd -r nixbld && chown root /nix
      for n in $(seq 1 10); do useradd -c "Nix build user $n" -d /var/empty -g nixbld -G nixbld -M -N -r -s "$(command -v nologin)" "nixbld$n"; done

  - name: create .zshrc config
    blockinfile:
      path: "/root/.zshrc"
      marker: "# {mark} - enable defaults - ANSIBLE MANAGED BLOCK"
      create: yes
      mode: 0600
      block: |
        # Lines configured by zsh-newuser-install
        HISTFILE=~/.histfile
        HISTSIZE=1000
        SAVEHIST=1000
        # End of lines configured by zsh-newuser-install
        # The following lines were added by compinstall
        zstyle :compinstall filename '/home/nik/.zshrc'

        autoload -Uz compinit
        compinit
        # End of lines added by compinstall
        source $HOME/.nix-profile/etc/profile.d/nix.sh
